import type { DocumentRecord } from "./types";

/**
 * Mock document data. In a real app this would come from an API / server
 * component fetch; the table component stays agnostic to the source.
 */
const rawDocuments: DocumentRecord[] = [
  {
    id: "1",
    name: "License Document",
    type: "Credential",
    issuedDate: "01-01-2026",
    expiryDate: null,
    uploadedBy: "Dr. Patel",
    status: "verified",
    description: "Medical practice license verification document.",
    uploadUrl: "/documents/license-doc.pdf",
  },
  {
    id: "2",
    name: "Health Policy",
    type: "Policy",
    issuedDate: "12-02-2026",
    expiryDate: "12-02-2027",
    uploadedBy: "Admin",
    status: "pending",
    description: "Annual health insurance and liability policy statement.",
    uploadUrl: "/documents/health-policy.pdf",
  },
  {
    id: "3",
    name: "Lab Report",
    type: "Medical",
    issuedDate: "01-01-2026",
    expiryDate: null,
    uploadedBy: "Dr. Shah",
    status: "verified",
    description: "Blood test chemistry and hematology laboratory report.",
    uploadUrl: "/documents/lab-report.pdf",
  },
  {
    id: "4",
    name: "License Document",
    type: "Credential",
    issuedDate: "01-01-2026",
    expiryDate: null,
    uploadedBy: "Dr. Mehta",
    status: "verified",
    description: "State medical board accreditation license registration.",
    uploadUrl: "/documents/state-license.pdf",
  },
  {
    id: "5",
    name: "Fitness Certificate",
    type: "Medical",
    issuedDate: "01-01-2026",
    expiryDate: null,
    uploadedBy: "Nurse Megha",
    status: "expiry",
    description: "Physical wellness and fitness examination certificate.",
    uploadUrl: "/documents/fitness-cert.pdf",
  },
  {
    id: "6",
    name: "Health Policy",
    type: "Credential",
    issuedDate: "21-03-2026",
    expiryDate: "21-03-2027",
    uploadedBy: "Dr. Patel",
    status: "expiry",
    description: "Professional indemnity coverage and health policy details.",
    uploadUrl: "/documents/indemnity-policy.pdf",
  },
  {
    id: "7",
    name: "Lab Report",
    type: "Medical",
    issuedDate: "01-01-2026",
    expiryDate: null,
    uploadedBy: "Dr. Trivedi",
    status: "pending",
    description: "Cardiology screening and electrocardiogram laboratory report.",
    uploadUrl: "/documents/cardiology-report.pdf",
  },
  {
    id: "8",
    name: "Safety certificate",
    type: "Medical",
    issuedDate: "01-01-2026",
    expiryDate: null,
    uploadedBy: "Safety Officer",
    status: "verified",
    description: "Occupational safety and hazard prevention certificate.",
    uploadUrl: "/documents/safety-cert.pdf",
  },
  {
    id: "9",
    name: "Vaccination Record",
    type: "Medical",
    issuedDate: "10-04-2026",
    expiryDate: null,
    uploadedBy: "Nurse Megha",
    status: "verified",
    description: "COVID-19 and influenza immunization history record.",
    uploadUrl: "/documents/vaccination-record.pdf",
  },
  {
    id: "10",
    name: "Clinical Guideline",
    type: "Policy",
    issuedDate: "15-04-2026",
    expiryDate: "15-04-2028",
    uploadedBy: "Admin",
    status: "verified",
    description: "Standard operating procedure and hygiene protocol document.",
    uploadUrl: "/documents/hygiene-protocol.pdf",
  },
  {
    id: "11",
    name: "DEA Registration",
    type: "Credential",
    issuedDate: "01-05-2026",
    expiryDate: "01-05-2029",
    uploadedBy: "Dr. Patel",
    status: "verified",
    description: "Drug Enforcement Administration practitioner certificate.",
    uploadUrl: "/documents/dea-registration.pdf",
  },
  {
    id: "12",
    name: "NPI Confirmation",
    type: "Credential",
    issuedDate: "12-05-2026",
    expiryDate: null,
    uploadedBy: "Admin",
    status: "verified",
    description: "National Provider Identifier registry registration confirmation.",
    uploadUrl: "/documents/npi-registry.pdf",
  },
  {
    id: "13",
    name: "X-Ray Report",
    type: "Medical",
    issuedDate: "20-05-2026",
    expiryDate: null,
    uploadedBy: "Dr. Shah",
    status: "pending",
    description: "Chest radiograph and diagnostic imaging assessment.",
    uploadUrl: "/documents/chest-xray.pdf",
  },
  {
    id: "14",
    name: "CLIA Certificate",
    type: "Credential",
    issuedDate: "25-05-2026",
    expiryDate: "25-05-2027",
    uploadedBy: "Safety Officer",
    status: "expiry",
    description: "Clinical Laboratory Improvement Amendments accreditation document.",
    uploadUrl: "/documents/clia-cert.pdf",
  },
  {
    id: "15",
    name: "HIPAA Training Cert",
    type: "Credential",
    issuedDate: "01-06-2026",
    expiryDate: "01-06-2027",
    uploadedBy: "Admin",
    status: "verified",
    description: "Annual patient privacy and HIPAA compliance training certificate.",
    uploadUrl: "/documents/hipaa-training.pdf",
  },
  {
    id: "16",
    name: "Pathology Analysis",
    type: "Medical",
    issuedDate: "05-06-2026",
    expiryDate: null,
    uploadedBy: "Dr. Trivedi",
    status: "pending",
    description: "Tissue biopsy pathology analysis report.",
    uploadUrl: "/documents/biopsy-analysis.pdf",
  },
  {
    id: "17",
    name: "BLS Certification",
    type: "Credential",
    issuedDate: "10-06-2026",
    expiryDate: "10-06-2028",
    uploadedBy: "Nurse Megha",
    status: "verified",
    description: "Basic Life Support and CPR credential for healthcare providers.",
    uploadUrl: "/documents/bls-cert.pdf",
  },
  {
    id: "18",
    name: "Malpractice Insurance",
    type: "Policy",
    issuedDate: "15-06-2026",
    expiryDate: "15-06-2027",
    uploadedBy: "Admin",
    status: "expiry",
    description: "Medical malpractice professional liability insurance certificate.",
    uploadUrl: "/documents/malpractice-insurance.pdf",
  },
  {
    id: "19",
    name: "Prescription Log",
    type: "Medical",
    issuedDate: "22-06-2026",
    expiryDate: null,
    uploadedBy: "Dr. Mehta",
    status: "verified",
    description: "Controlled substances prescription audits log summary.",
    uploadUrl: "/documents/prescription-log.pdf",
  },
  {
    id: "20",
    name: "Fire Safety Approval",
    type: "Policy",
    issuedDate: "30-06-2026",
    expiryDate: "30-06-2027",
    uploadedBy: "Safety Officer",
    status: "pending",
    description: "Facility annual fire safety audit and clearance approval.",
    uploadUrl: "/documents/fire-safety.pdf",
  },
];

export const documents: DocumentRecord[] = rawDocuments.map((doc) => ({
  ...doc,
  uploadUrl: `https://dummyjson.com/image/400x200/008080/ffffff?text=${encodeURIComponent(
    doc.description
  ).replace(/%20/g, "+")}&fontSize=16&fontFamily=poppins`,
}));

/** Summary counts shown in the stats bar. */
export const documentStats = {
  credential: documents.filter((doc) => doc.type === "Credential").length,
  verified: documents.filter((doc) => doc.status === "verified").length,
  pending: documents.filter((doc) => doc.status === "pending").length,
  expiringSoon: documents.filter((doc) => doc.status === "expiry").length,
};

/** Total records the paginated table represents. */
export const totalDocuments = documents.length;
